### ISSUE TITLE
Fix Google Structured data

### ISSUE THREAD

**Issue by arcanistzed** [HacktheHill/2023.hackthehill.com#101]
https://www.google.com/webmasters/markup-helper/u/0/

![Image](https://user-images.githubusercontent.com/82790112/215366824-d6f9a140-bdf7-4aec-a940-e54057c7241f.png)

**Comment by Arjuunan** [comment]
For reference: 
https://developers.google.com/search/docs/appearance/structured-data/event
https://search.google.com/test/rich-results/result/r%2Fevents?id=VPZjBo1v9rr-qVssIk1BjA
