### ISSUE TITLE
Missing `text-align: center`

### ISSUE THREAD

**Issue by arcanistzed** [HacktheHill/2023.hackthehill.com#136]
`text-align: center` is needed in `.footer-slogan` and `.event-title`

**Comment by this-is-sky** [comment]
Hi, Can you please assign this issue to me?

Thanks!

**Comment by arcanistzed** [comment]
Hey @this-is-sky, thank you for offering to help. Unfortunately we don't have the capacity to accept external contributions at this time. I will let you know if this policy changes in the future.
