### ISSUE TITLE
Remove MUI

### ISSUE THREAD

**Issue by arcanistzed** [HacktheHill/2023.hackthehill.com#84]
Remove all of the uses of MUI components for stuff like Boxes, Stacks, Grids, Buttons, etc. since using CSS is more flexible.

We can keep the accordion for now since that's something that a library is much more useful for.

**Comment by xsachax** [comment]
This issue is only in the schedule section (except for the accordion in FAQ). We can remove the accordion as a last task if we have time.

This issue also involves removing all the CSS-in-JS to have better CSS and cleaner code.
